- name: Check service status
  command: systemctl status "{{ item }}"
  with_items:
    - kresd@1
    - nginx
    - nginx-exporter
  register: result
  ignore_errors: yes
  changed_when: false

- name: Check IPv4 NSID query
  shell: dig @{{ wg.ip }} -4 +nsid | grep NSID
  register: this
  failed_when: "inventory_hostname not in this.stdout"
  changed_when: false

- name: Check IPv6 NSID query
  shell: dig @{{ wg.ip }} -6 +nsid | grep NSID
  register: this
  failed_when: "inventory_hostname not in this.stdout"
  changed_when: false

# - name: Check DNSSEC OK query
#   shell: dig @{{ wg.ip }} +short sigok.verteiltesysteme.net
#   register: this
#   failed_when: "'.' not in this.stdout"
#   changed_when: false

# - name: Check DNSSEC FAIL query
#   shell: dig @{{ wg.ip }} +short sigfail.verteiltesysteme.net
#   register: this
#   failed_when: this.stdout != ""
#   changed_when: false

- name: Check QNAME minimization
  shell: dig @{{ wg.ip }} +short TXT qnamemintest.internet.nl
  register: this
  failed_when: "'QNAME minimisation is enabled' not in this.stdout"
  changed_when: false

- name: Check DoT NSID query
  shell: kdig +tls +nsid @dns.emeraldonion.org | grep NSID
  register: this
  failed_when: "inventory_hostname not in this.stdout"
  changed_when: false

- name: Check DoH NSID query
  shell: kdig +https +nsid @dns.emeraldonion.org | grep NSID
  register: this
  failed_when: "inventory_hostname not in this.stdout"
  changed_when: false
